### ISSUE TITLE
Syntax error in database initializers

### ISSUE THREAD

**Issue by akshettrj** [TeamUltroid/pyUltroid#57]
* In the file: `pyUltroid/startup/_database.py - lines 198,205 & 215`, there is a syntax error in the `ALTER TABLE` database commands. In the latest commit, there is an extra pair of round-brackets `()` around the column names placeholder which should not be there.

* Current:
```py
    def set_key(self, key, value):
        try:
            self._cursor.execute(
                f"ALTER TABLE Ultroid DROP COLUMN IF EXISTS (%s)", (str(key),)
            )
```

* Fixed:
```py
    def set_key(self, key, value):
        try:
            self._cursor.execute(
                f"ALTER TABLE Ultroid DROP COLUMN IF EXISTS %s", (str(key),)
            )
```

* Similarly, changes need to be made in the rest of the two places

**Comment by xditya** [comment]
Please feel free to open a pull request, if you have the time, or wait for someone among the devs to sort it out. Thanks!

**Comment by kaif-00z** [comment]
ig Fixed by devesh 

https://github.com/TeamUltroid/pyUltroid/commit/e8a37bc671539a949e969831372ad46221523251

**Comment by akshettrj** [comment]
> ig Fixed by devesh
> 
> [e8a37bc](https://github.com/TeamUltroid/pyUltroid/commit/e8a37bc671539a949e969831372ad46221523251)

Oh! My bad I did not check the dev branch

Sorry for inconvenience
